# This workflow will perform archinaut analysis on the project and generate a report
# on the metrics analyzed

# This is the name of the workflow
name: Archinaut analysis
on: [push]
jobs:
  archinaut-analysis:
    runs-on: ubuntu-latest
    name: Archinaut analysis
    steps:
      # Check out our repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Do the Archinaut analysis over the last month of commits
      - name: Analysis
        id: archinaut
        uses: hdmsantander/archinaut-action@main
        with:
          configuration file: archinaut.yml
          init date: '2020-03-07'
          min cochanges: 0
          scc cloc: 1000
          scc complexity: 19
          scc loc: 1200
      
      # Run Archinaut companion action to upload
      - name: Archinaut companion
        id: archinaut-companion
        uses: hdmsantander/archinaut-companion-action@main
        with:
          results: ${{ env.workspace }} archinaut.csv
          
      # Analyze JUnit threshold report
      - name: Generate report using Archinaut XML output
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
         check_name: 'Archinaut analysis results'
         report_individual_runs: true
         github_token: ${{ secrets.GITHUB_TOKEN }}
         files: archinaut.xml

      # Store the Archinaut results artifact
      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v2
        with:
          name: archinaut-csv
          path: archinaut.csv
          
      # Store the Archinaut JUnit artifact
      - name: Upload XML as artifact
        uses: actions/upload-artifact@v2
        with:
          name: archinaut-junit
          path: archinaut.xml
          
      # Store the Archinaut JSON results
      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v2
        with:
          name: archinaut-json
          path: archinaut.json
